from .graph_operations import get_graphs_one_slide
#spared.graph_operations.get_graphs_one_slide

from .graph_operations import get_sin_cos_positional_embeddings
#spared.graph_operations.get_sin_cos_positional_embeddings

from .graph_operations import get_graphs
#spared.graph_operations.get_graphs